### ISSUE TITLE
please move the documentation to github

### ISSUE THREAD

**Issue by Zane-XY** [mtedone/podam#103]
the URL 
http://home.btconnect.com/jemosAgile/projects/podam/walk-through-example.html
contains the documentation is not accessible, it gives:

The requested URL was rejected. If you think this is an error, please contact the webmaster.

Your support ID is: 15891905563417259022

**Comment by daivanov** [comment]
URL you provided is accessible. I believe you have an issue with your proxy server. However, btconnect is old website containing outdated information. The new website is http://mtedone.github.io/podam/walk-through-example.html.

**Comment by mtedone** [comment]
Changed the Project Header to include the new home URL

**Comment by mtedone** [comment]
Added URL to new home page to pom.xml
