### ISSUE TITLE
allow the annotation to be used on getters

### ISSUE THREAD

**Issue by Zane-XY** [mtedone/podam#105]
The major usage of random initialized objects is for testing, (I personally think) it's not a good idea to put podam annotation into pojos. If it allows to put the annotations on getters, the following would be possible:
```java
class PetProxy extends Pet {

    // podam annotation
    public String getName() {... };
}
```

What do you think?

**Comment by mtedone** [comment]
Annotations are just another tool offered by Podam to developers to customise Podam's behaviour. There are other ways (the recommended ones) to customise Podam, e.g. provide your own data provider strategy, external factory, etc.

**Comment by daivanov** [comment]
Podam allows to put annotations on fields, constructor and setter parameters. What would be use case for adding annotations to getters?
