### ISSUE TITLE
Unused fields in AbstractRandomDataProviderStrategy.addAttributeStrategy() and AbstractRandomDataProviderStrategy.addSpecific(). The Javadoc for these two methods is incorrect as does not specify a correct contract. 

### ISSUE THREAD

**Issue by daivanov** [mtedone/podam#106]
Calling AbstractRandomDataProviderStrategy.addAttributeStrategy() and AbstractRandomDataProviderStrategy.addSpecific() has no effect if there is already mapping or attribute strategy present.

Despite JavaDocs specifies correct behavior:
http://mtedone.github.io/podam/apidocs/uk/co/jemos/podam/api/AbstractRandomDataProviderStrategy.html#addSpecific-java.lang.Class-java.lang.Class-

https://github.com/mtedone/podam/blob/cf7d7fda9b50bb767ce809bf7d9342fdfad41e1d/src/main/java/uk/co/jemos/podam/api/AbstractRandomDataProviderStrategy.java#L540

https://github.com/mtedone/podam/blob/cf7d7fda9b50bb767ce809bf7d9342fdfad41e1d/src/main/java/uk/co/jemos/podam/api/AbstractRandomDataProviderStrategy.java#L598

Both methods define unused variable aClass and attributeStrategyClass

	Class<?> aClass = specificTypes.putIfAbsent(abstractClass, specificClass);
	if (null == aClass) {
		aClass = specificClass;
	}

	Class<AttributeStrategy<?>> attributeStrategyClass = attributeStrategies.putIfAbsent(annotationClass, strategyClass);
	if (null == attributeStrategyClass) {
		attributeStrategyClass = strategyClass;
	}

**Comment by mtedone** [comment]
This is the correct behaviour as if there's already an element present nothing should be done. If replacement is needed them the method signature should be called differently, e.g. Replace atrributeStrategy and replaceSpecific. So the issue should be renamed to: remove unused fields. This is no side effect as a side effect has ripercussions outside method context. Unused fields have no ripercussions outside the method context.

**Comment by mtedone** [comment]
Fixed in 5.4.1-SNAPSHOT

**Comment by daivanov** [comment]
When I call AbstractRandomDataProviderStrategy.addSpecific() I want to be sure this call takes effect. Current behavior is incorrect.

**Comment by mtedone** [comment]
What do you mean by takes effect? Currently it adds the element if it's not there, otherwise it doesn't add it.

**Comment by daivanov** [comment]
This test

	@Test
	public void testPut() throws Exception {
		ConcurrentHashMap<String, String> map = new ConcurrentHashMap<String, String>();
		map.putIfAbsent("key", "first");
		String value = map.get("key");
		assertEquals("first", value);
		map.putIfAbsent("key", "second");
		value = map.get("key");
		assertEquals("second", value);
	}

results in:

        Failed tests:   testPut(org.indt.AppTest): expected:<[second]> but was:<[first]>

so that all sequential calls of addSpecific result in no-op, which is obviously undesired behavior. `putIfAbsent` at least returns value, which caller can check, but addSpecific return `this` for chaining, so caller will be left to wonder was this operation successful or not. This is *really bad* API.

**Comment by mtedone** [comment]
That's the correct behaviour. A Map holds only one value per key. So the semantic of addSpecific means add an element to the map. What you're describing is an addOrReplace functionality and if you want that you should write an implementation for it. Add means "Add", it doesn't mean "Replace".

**Comment by daivanov** [comment]
This is unpredictable behavior, so it cannot be correct. Now addSpecific() must be precedeed by removeSpecific() just to be sure that call takes an effect. You are right, that "add" means "add", it doesn't mean addIfAbsent. Map.put() does exactly what this method was doing, then should it be putOrReplace?

This is too much to have addSpecific and addOrReplace for this functionality.
And RadnomDataProvider is only one of implementations. Another one could be backed by the key <-> Set mapping, where single interface maps to its multiple implementations. Then addOrReplace() call makes no sense.

This is serious regression and it must be fixed.
