### ISSUE TITLE
Trying to fill data in a property of an interface type

### ISSUE THREAD

**Issue by deanclkclk** [mtedone/podam#107]
Hey guys:

Love the plugin. I'm trying to fill data in this object https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/client/BaseClientDetails.java. However, as you can see there's a property called `authorities` of type ***GrantedAuthority*** (line 69). This type is an interface and whenever I try to create the object with `factory.manufacturePojo` I get the issue that it's not able to instantiate an interface (which is understandable.). Is there a way to supply to ***PodamFactory*** that whenever it encounters that interface, it should use a specific base class to instantiate?

**Comment by mtedone** [comment]
You can use RandomDataProviderStrategy.addSpecific to bind an interface/abstract class to a concrete type.

**Comment by deanclkclk** [comment]
Will d @mtedone thanks again.

**Comment by mtedone** [comment]
Update: in the latest version, I've renamed addSpecific... to addOrReplaceSpecific. The rest remains unchanged

**Comment by deanclkclk** [comment]
Thanks again @mtedone. I'll close this ticket for now.
