### ISSUE TITLE
Codeship error running Podam

### ISSUE THREAD

**Issue by dbclkclk** [mtedone/podam#108]
Hey Guys:

Again, great plugin. I'm having a peculiar issue running the plugin on my build system (codeship). My tests pass locally but, on Codeship, I get these errors:

         		Test set: com.xxxxx.api.services.CustomClientDetailsServiceImplUnitTest
		-------------------------------------------------------------------------------
		Tests run: 11, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.001 sec <<< F
		AILURE! - in com.xxxxx.api.services.CustomClientDetailsServiceImplUnitTest
		testAddClientDetailsThatIfRecordExistShouldThrowException(com.xxxxx.api.se
		rvices.CustomClientDetailsServiceImplUnitTest)  Time elapsed: 0 sec  <<< ERROR!
		java.lang.Exception: Unexpected exception, expected<org.springframework.security
		.oauth2.provider.ClientAlreadyExistsException> but was<java.lang.NoSuchMethodErr
		or>
				at uk.co.jemos.podam.api.AbstractRandomDataProviderStrategy.addSpecific(
		AbstractRandomDataProviderStrategy.java:505)
				at com.xxxxx.api.services.CustomClientDetailsServiceImplUnitTest.t
		estAddClientDetailsThatIfRecordExistShouldThrowException(CustomClientDetailsServ
		iceImplUnitTest.java:184)

		testUpdateClientDetailsThatItSavesOauthClientDetailsObject(com.xxxxx.api.s
		ervices.CustomClientDetailsServiceImplUnitTest)  Time elapsed: 0 sec  <<< ERROR!
		java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/l
		ang/Object;)Ljava/lang/Object;
				at uk.co.jemos.podam.api.AbstractRandomDataProviderStrategy.addSpecific(
		AbstractRandomDataProviderStrategy.java:505)
		@

The specific test in question:

     			@ContextConfiguration(locations = {"classpath:"})
		public class CustomClientDetailsServiceImplUnitTest {

			CustomClientDetailsServiceImpl customClientDetailsServiceImpl = new CustomClientDetailsServiceImpl();

			OauthClientDetailsRepository mockOauthClientDetailsRepository;

			PasswordEncoder mockPasswordEncoder;

			@Before
			public void setUp() {

				this.mockOauthClientDetailsRepository = Mockito.mock(OauthClientDetailsRepository.class);
				this.mockPasswordEncoder = Mockito.mock(PasswordEncoder.class);

				this.customClientDetailsServiceImpl.setRepository(this.mockOauthClientDetailsRepository);
				this.customClientDetailsServiceImpl.setPasswordEncoder(this.mockPasswordEncoder);

			}

			@Test
			public void testLoadClientByClientIdThatItFetchesClient() {
				PodamFactory factory = new PodamFactoryImpl();
				OauthClientDetails oauthClientDetails = factory.manufacturePojo(OauthClientDetails.class);
				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(oauthClientDetails);
				ClientDetails result = this.customClientDetailsServiceImpl.loadClientByClientId("");
				Assert.assertNotNull(result);

			}

			@Test(expected = NoSuchClientException.class)
			public void testLoadClientByClientIdThatIfNoClientExistShouldThrowError() {
				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(null);
				this.customClientDetailsServiceImpl.loadClientByClientId("");

			}

			@Test
			public void testUpdateClientSecretTestThatClientSecretIsUpdated() {
				PodamFactory factory = new PodamFactoryImpl();
				OauthClientDetails oauthClientDetails = factory.manufacturePojo(OauthClientDetails.class);
				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(oauthClientDetails);
				Mockito.when(this.mockPasswordEncoder.encode(Mockito.anyString())).thenReturn("");
				Mockito.when(this.mockOauthClientDetailsRepository.save(Mockito.any(OauthClientDetails.class))).thenReturn(null);

				this.customClientDetailsServiceImpl.updateClientSecret("","");

				Mockito.verify(this.mockOauthClientDetailsRepository, Mockito.times(1)).save(Mockito.any(OauthClientDetails.class));
				Mockito.verify(this.mockPasswordEncoder, Mockito.times(1)).encode(Mockito.anyString());

			}
			@Test(expected = NoSuchClientException.class)
			public void testUpdateClientSecretThrowsExceptionWhenClientDoesNotExist() {

				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(null);
				this.customClientDetailsServiceImpl.updateClientSecret("", "");
			}

			@Test
			public void testRemoveClientDetailsThatItDeletesRecord() {

				PodamFactory factory = new PodamFactoryImpl();
				OauthClientDetails oauthClientDetails = factory.manufacturePojo(OauthClientDetails.class);

				Mockito.doNothing().when(this.mockOauthClientDetailsRepository).delete(Mockito.any(OauthClientDetails.class));

				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(oauthClientDetails);

				this.customClientDetailsServiceImpl.removeClientDetails("");

				Mockito.verify(this.mockOauthClientDetailsRepository, Mockito.times(1)).delete(Mockito.any(OauthClientDetails.class));
			}

			@Test(expected = NoSuchClientException.class)
			public void testRemoveClientDetailsThatItThrowsErrorWhenClientDetailsNotFound() {

				Mockito.doNothing().when(this.mockOauthClientDetailsRepository).delete(Mockito.any(OauthClientDetails.class));

				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(null);

				this.customClientDetailsServiceImpl.removeClientDetails("");

				Mockito.verify(this.mockOauthClientDetailsRepository, Mockito.times(0)).delete(Mockito.any(OauthClientDetails.class));
			}

			@Test
			public void testListClientDetailsThatItReturnsAListOfClientDetailsObjects()
			{
				PodamFactory factory = new PodamFactoryImpl();
				List<OauthClientDetails> oauthClientDetails = new ArrayList<OauthClientDetails>();
				oauthClientDetails.add(factory.manufacturePojo(OauthClientDetails.class));
				oauthClientDetails.add(factory.manufacturePojo(OauthClientDetails.class));

				Mockito.when(this.mockOauthClientDetailsRepository.findAll()).thenReturn(oauthClientDetails);

				List<ClientDetails> results = this.customClientDetailsServiceImpl.listClientDetails();

				Assert.assertEquals(results.size(), oauthClientDetails.size());

			}

			@Test
			public void testListClientDetailsThatIfReturnsEmptyListMethodRetunsNull()
			{
				Mockito.when(this.mockOauthClientDetailsRepository.findAll()).thenReturn(null);

				List<ClientDetails> results = this.customClientDetailsServiceImpl.listClientDetails();

				Assert.assertTrue(results.size() == 0);

			}

			@Test
			public void testAddClientDetailsThatItSavesOauthClientDetailsObject()
			{

				PodamFactory factory = new PodamFactoryImpl();
				((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(GrantedAuthority.class, SimpleGrantedAuthority.class);

				BaseClientDetails baseClientDetails = factory.manufacturePojo(BaseClientDetails.class);

				baseClientDetails.setAdditionalInformation(new HashMap<String, Object>(){{
						put("test","test");
						put("test1","test1");
				}});

				Mockito.when(this.mockOauthClientDetailsRepository.save(Mockito.any(OauthClientDetails.class))).thenReturn(null);

				this.customClientDetailsServiceImpl.addClientDetails(baseClientDetails);

				Mockito.verify(this.mockOauthClientDetailsRepository,Mockito.times(1)).save(Mockito.any(OauthClientDetails.class));
			}

			@Test(expected = ClientAlreadyExistsException.class)
			public void testAddClientDetailsThatIfRecordExistShouldThrowException()
			{

				PodamFactory factory = new PodamFactoryImpl();
				((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(GrantedAuthority.class, SimpleGrantedAuthority.class);

				BaseClientDetails baseClientDetails = factory.manufacturePojo(BaseClientDetails.class);

				baseClientDetails.setAdditionalInformation(new HashMap<String, Object>() {{
					put("test", "test");
					put("test1", "test1");
				}});

				Mockito.when(this.mockOauthClientDetailsRepository.save(Mockito.any(OauthClientDetails.class))).thenThrow(new DataIntegrityViolationException(""));

				this.customClientDetailsServiceImpl.addClientDetails(baseClientDetails);
			}

			@Test
			public void testUpdateClientDetailsThatItSavesOauthClientDetailsObject()
			{

				PodamFactory factory = new PodamFactoryImpl();
				((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(GrantedAuthority.class, SimpleGrantedAuthority.class);

				BaseClientDetails baseClientDetails = factory.manufacturePojo(BaseClientDetails.class);

				baseClientDetails.setAdditionalInformation(new HashMap<String, Object>(){{
					put("test","test");
					put("test1","test1");
				}});

				OauthClientDetails oauthClientDetails = factory.manufacturePojo(OauthClientDetails.class);

				Mockito.when(this.mockOauthClientDetailsRepository.findOne(Mockito.any(Specification.class))).thenReturn(oauthClientDetails);

				Mockito.when(this.mockOauthClientDetailsRepository.save(Mockito.any(OauthClientDetails.class))).thenReturn(new OauthClientDetails());

				this.customClientDetailsServiceImpl.updateClientDetails(baseClientDetails);

				Mockito.verify(this.mockOauthClientDetailsRepository, Mockito.times(1)).save(Mockito.any(OauthClientDetails.class));
			}
		}

**Comment by mtedone** [comment]
Which version are you running?

**Comment by deanclkclk** [comment]
Currently using version 5.4.0.RELEASE of podam. It's really weird as I have all my test passing locally.

**Comment by dbclkclk** [comment]
@mtedone I missed something in my first post (stacktrace for the error). I updated it.

**Comment by mtedone** [comment]
OK, try 5.4.1.RELEASE and if that doesn’t work you’ll need to get the latest master SNAPSHOT. 5.4.0.RELEASE didn’t run on Java 6/7 JVMs. 

Let me know if that works. 

Regards,

**Comment by dbclkclk** [comment]
@mtedone that version now running maven test shows:

     Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal

I added this to my maven pom.xml

      <dependency>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
					<version>2.0.2</version>
				</dependency>

Doesn't seem to help

**Comment by dbclkclk** [comment]
Got this fixed by downgrading to xml-apis 1.4.01.
