### ISSUE TITLE
Limit max string length for @Size

### ISSUE THREAD

**Issue by yuppie-flu** [mtedone/podam#110]
There is an issue with generation String fields marked Size annotation with only min value parameter.

    @Size(min = 1)
    private String name;

In such case max value parameter is Integer.MAX_INT, so BeanValidationStrategy tries to create string with length [min, Integer.MAX_INT]. This action usually ends up with OOM exception.
Is it possible to limit max length of generated string by some reasonable constant (10 for example)?
Or maybe there is some other way to overcome this problem without modifying source code of domain objects (can't use PodamStringValue annotation or add max parameter)?

**Comment by mtedone** [comment]
Fixed in 5.5.1.RELEASE

https://github.com/mtedone/podam/commit/0b007eb861f2c531f64e5070915ebc0a81a2bc53
