### ISSUE TITLE
Problem with Log4j2

### ISSUE THREAD

**Issue by raulvillalbamedina** [mtedone/podam#114]
With the version 5.5.1.RELEASE when you use log4 1.2.17 we have a problem.
The tests read log4j2.xml from podam jar and not use 1.2.17 configuration.
We try exclude log jars from podam dependency but the tests say "not found LogManager" from org.apache.logging.log4j

https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/LogManager.html

We move to 5.4.1.RELEASE and this version is Ok

**Comment by mtedone** [comment]
This is not an issue. Podam has moved to log4j2 and I'd recommend for you
to do the same?

**Comment by raulvillalbamedina** [comment]
This is a bug, podam use slf4j with log4j2 implementation. And other persons use logback or log4j or other implementation. Libraries like Podam cannot define my log implementation. The change is simple, not use classes implementeds in log4j2, use the interfaces of slf4j.
LogManager exist in slf4j

**Comment by mtedone** [comment]
Closed: f881fc30ba18bf73618124fb4409ba559554f5c0

**Comment by raulvillalbamedina** [comment]
thanks!
