### ISSUE TITLE
podam are slow with objects with lists

### ISSUE THREAD

**Issue by raulvillalbamedina** [mtedone/podam#117]
With last versions the time to fill some objects with lists are very slow.
Now 21.262 sec
Before 3.123 sec

some mode to set default max limits in lists?

**Comment by mtedone** [comment]
Yes create a custom strategy and set the number of collection elements
there. Alternatively you can use the @PodamCollection annotation.

Regards,

**Comment by mtedone** [comment]
Also, you can retrieve the strategy from the factory and set memoization to true.

Regards,
