### ISSUE TITLE
A Pojo does not need to have getters and setters, but fields are not set by Podam

### ISSUE THREAD

**Issue by convoi** [mtedone/podam#118]
Take this class for example.
```java
public class NoSetters implements Serializable{
    private Date date;
    public NoSetters() {}

    public void init() {
        date = new Date();
    }

    public Date getDate() {
        return date;
    }
}
```
Podam fails to populate the date field.
I'm wondering why podam seems to rely on getters and setters at all an not just use reflection to scan for fields and then set these fields via reflection.
From the name and description i would expect it to not rely on setters and getters to even exist.
>PODAM - POjo DAta Mocker
>Podam (http://mtedone.github.io/podam/) is a Java testing tool which auto-fills POJOs with made-up data.

**Comment by daivanov** [comment]
Because setting private fields with random values will break internal state of quite a few objects. Encapsulation exists for a reason.

**Comment by mtedone** [comment]
First, Podam was created as a tool to fill in JavaBeans, which need to have getters and setters. Secondly, we've added support for a number of cases to accommodate more generic POJOs, e.g. full constructors and also the ability to specify your own methods to fill in attributes. So users have got all they need to circumvent JavaBean standards as long as they use the library properly.

**Comment by daivanov** [comment]
Take this class for example

    import java.io.Serializable;
    import java.security.GeneralSecurityException;
    import java.security.KeyFactory;
    import java.security.PublicKey;
    import java.security.spec.X509EncodedKeySpec;

    import javax.xml.bind.DatatypeConverter;

    public class Pojo implements Serializable {
        private static final long serialVersionUID = 1L;

        private byte[] publicKey;

        public Pojo(PublicKey publicKey) {
            this.publicKey = publicKey.getEncoded();
        }

        public PublicKey getPublicKey() {
            PublicKey key = null;
            try {
                X509EncodedKeySpec pubKeySpec = new X509EncodedKeySpec(publicKey);
                KeyFactory keyFactory = KeyFactory.getInstance("RSA");
                key = keyFactory.generatePublic(pubKeySpec);
            } catch(GeneralSecurityException e) {
                System.out.println("Public key '" + DatatypeConverter.printHexBinary(publicKey)
                        + "' is messed up");
            }
            return key;
        }
    }

This is a proper POJO, but due to the fact PublicKey is not Serializable, it's being converted to byte array and back. Filling byte array representing key directly will result in POJO with broken internal state. And there is no way around that since reflection cannot know, what these fields should be and what they are used for.
