### ISSUE TITLE
Strategy for custom date

### ISSUE THREAD

**Issue by dbclkclk** [mtedone/podam#126]
Regarding the strategy method to override for custom date, when instantiate an object's property of type date. Looking at `AbstractRandomDataProviderStrategy`, I'm not sure which method i should override regarding custom dates.

**Comment by mtedone** [comment]
Hi Dean for non primitives and Object Podam will use introspection to
create an object, using either the default or fullest constructor depending
on what method you invoked to manufacture your object. To set custom dates,
provided they result in the same Date type, you can use the
attributemetadata object, intercept the field name you want to customise
and return your special value. The tests have examples on how to use
attributemetadata to customise values.

Hope this helps.

Regards,

**Comment by fani1983** [comment]
Hi for non primitives and Object Podam will use introspection to
create an object, using either the default or fullest constructor depending
on what method you invoked to manufacture your object. To set custom dates,
provided they result in the same Date type, you can use the
attributemetadata object, intercept the field name you want to customise
and return your special value. The tests have examples on how to use
attributemetadata to customise values.
