### ISSUE TITLE
Annotation for cached manufacturePojo

### ISSUE THREAD

**Issue by tomasbjerre** [mtedone/podam#190]
I am currently doing somehing like:
```
  PodamFactory factory = new PodamFactoryImpl();
  NotificationDTO originalDto = factory.manufacturePojo(NotificationDTO.class);
```

I want to do something like:
```
 @PodamObject
 private NotificationDTO originalDto;
```

Where
 * originalDto would be assigned an instance of NotificationDTO.
 * The instance is cached so that another test that wants an instance is getting the same one.

I cant find it in the docs, is it possible? Would a PR for this be accepted?

**Comment by mtedone** [comment]
Try looking at http://mtedone.github.io/podam/annotations.html

And at the AnnotationTest class, test named: podamShouldAssignExactValuesDefinedInPodamStrategyValueAnnotation

As for caching values, this is driven by the memoization. Memoization is enabled by default. This means that if an object is created Podam won't recreate it. More can be found here (look at "Tweaking Podam for performance"): 

http://mtedone.github.io/podam/

Hope this helps

**Comment by tomasbjerre** [comment]
Should I interpret the answer as no? I cannot see any annotation there that does exactly what `factory.manufacturePojo(NotificationDTO.class)` does. I think it would be nice to have an annotation that does that so that I can use in on an attribute in a unit test case.

Like [here](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/test/java/se/bjurr/prnfb/transformer/ButtonTransformerTest.java#L16). I'd like to move that variable to an attribute and annotate it instead of making that static call.

I really dont like the idea of adding Podam as a production dependency as it will add alot of  libs to the classpath, that are really only needed for testing.

**Comment by mtedone** [comment]
In fact you don’t have to touch your production code if you’re not using Podam other than for testing. 

You can create an attribute-level strategy as defined here:

**Comment by tomasbjerre** [comment]
Some part of you comment got lost there right? =)

What I mean is [here](http://mtedone.github.io/podam/annotations.html) for example this:
```
@PodamStrategyValue(PostCodeStrategy.class)
private String postCode;
```
Is an attribute on a POJO from a production source folder right?

**Comment by mtedone** [comment]
Apologies, I don’t understand what this email mean? 

To customise your attribute values you can use annotations (legacy, these came with the first version of Podam) or by using attribute level strategies. If you’re using Podam just for testing you can keep the strategies in test code, if you are using it in production (like some do) you can keep the strategies as part of your production code.
