### ISSUE TITLE
Documentation links don't work.

### ISSUE THREAD

**Issue by RaviH** [mtedone/podam#259]
Hi, I would like to use this tool but none of the documentation links seem to work i.e. they give 404.

**Comment by daivanov** [comment]
Hi,

There is a link on top of github page
https://mtedone.github.io/podam
and it works fine for me.
What links you are trying?

Thanks, Daniil

**Comment by RaviH** [comment]
Hi, 

I am sorry for not getting back sooner. The links in the README don't work:

http://devopsfolks.github.io/podam/

http://devopsfolks.github.io/podam/serenity/capabilities.html
