### ISSUE TITLE
Custom PodamFactory that was working with 7.0.5.RELEASE stopped working with 7.1.1.RELEASE

### ISSUE THREAD

**Issue by buraequete** [mtedone/podam#266]
The custom factory I am creating is as follows, updated for latest version;

	static PodamFactory buildBeanFactory() {
		PodamFactoryImpl factory = new PodamFactoryImpl((new AbstractRandomDataProviderStrategy(1) {
			@Override
			public int getMaxDepth(Class<?> type) {
				return -1;
			}
		}));
		((RandomDataProviderStrategy) factory.getStrategy())
				.addOrReplaceAttributeStrategy(PatternA.class, new PatternAStrategy())
				.addOrReplaceAttributeStrategy(PatternB.class, new PatternBStrategy())
				.addOrReplaceAttributeStrategy(PatternC.class, new PatternCStrategy())
				.addOrReplaceTypeManufacturer(LocalDateTime.class, (s, m, map) -> LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS))
		return factory;
	}

& the manufacture method does work, but basic type manufacturers are not working, any field but those targeted by above custom strategies are null; String, Boolean, Integer etc. fields without any annotations. I am unable to debug podam source code directly at this moment

I am not sure of the reason, I have no other configuration but above factory, then I simply do

	factory.manufacturePojo(pojoClass)

**Comment by daivanov** [comment]
Hi,

  Your report doesn't provide any insight on the problem. Podam has pretty good log, why would not you provide it?

Thanks, Daniil

**Comment by daivanov** [comment]
Yes, and you definitely want to remove getMaxDepth -1.

**Comment by daivanov** [comment]
Ok, thank you.
