### ISSUE TITLE
When reaching maxDepth, null value is placed in collection

### ISSUE THREAD

**Issue by shollander** [mtedone/podam#269]
If `maxDepth` is set to avoid too many levels of recursion, and the recursive object is located within a collection; then although `maxDepth` does prevent recursion beyond the specified depth, it will fill the collection with null values. For example, given this object structure:
```java
public class MyObject {
    private String name;
    private List<MyObject> children;
}
```
When `maxDepth` is reached, `myObject.children` will be equal to `[null, null, null, null, null]`.
I don't think this is the usual expected behavior. Normally, `null` should not be placed in a collection. I would expect it to just not set any value for the `children` field at all, leaving it to the class initialization default.

**Comment by shollander** [comment]
The value of depth that I am using is 2.

**Comment by daivanov** [comment]
I feel this is not a proper solution, as third party libraries not implementing Collection, List or Map interfaces will be handled differently. Also not much can be done for arrays.

**Comment by daivanov** [comment]
Podam 7.2.2 has been released
