### ISSUE TITLE
Unsupported features

### ISSUE THREAD

**Issue by luckyQing** [mtedone/podam#273]
1. Unsupported BigInteger、BigDecimal. etc
   PodamFactory factory = new PodamFactoryImpl();
   BigInteger bigInteger = factory.manufacturePojoWithFullData(BigInteger.class);

2. Nested generics are not supported. etc
   List<BasePageResp<ProductInfo>>

**Comment by daivanov** [comment]
Hi,

  1. manufacturePojoWithFullData is rather dangerous method as it tries to do it with constructor with the maximum parameters. Use manufacturePojo() instead or make custom TypeManufacturer for BigDecimal.
  2. List<BasePageResp> - there is no nested generics here. Could you please clarify what do you mean?

Thanks, Daniil

**Comment by luckyQing** [comment]
Hi, for example, I want to mock an object, “Resp<BasePageReq<App>>”, it will show me an error

**Comment by luckyQing** [comment]
For example, I want to mock an object, “Resp<BasePageReq<App>>”, it will show me an error

**Comment by luckyQing** [comment]
For example, I want to mock an object, `Resp<BasePageReq<App>>,` it will show me an error

**Comment by luckyQing** [comment]
For example, I want to mock an object, `Req<BasePageReq<App<List<String>>>>,` it will show me an error.

**Comment by luckyQing** [comment]
I want to have the following features:
`PodamFactory factory = new PodamFactoryImpl();

TypeReference typeReference = new TypeReference<Req<BasePageReq<App<List<String>>>>>() {
		};
Req<BasePageReq<App<List<String>>>> data2 = factory.manufacturePojoWithFullData(typeReference);`

**Comment by luckyQing** [comment]
In addition, if the value of the annotation like `PodamStringValue` can support one randomly from array, it feels better.
For example, `@PodamStringValue(value={"male", "female"})`

**Comment by daivanov** [comment]
> it will show me an error
What kind of error?

Thanks, Daniil

**Comment by daivanov** [comment]
Use custom TypeManufacturer instead of @PodamStringValue. People really avoid them, because it forces to add podam as dependency instead of test dependency.

**Comment by luckyQing** [comment]
Customizing TypeManufacturer is inconvenient. And it is more convenient to use annotations

**Comment by luckyQing** [comment]
It does not support this generic object, etc `Req<BasePageReq<App<List>>>`

**Comment by daivanov** [comment]
> Customizing TypeManufacturer is inconvenient. And it is more convenient to use annotations

You seems to be alone with that opinion so far.

> It does not support this generic object, etc `Req<BasePageReq<App<List>>>`

I need either code to reproduce the issue or at least Podam's log.

Thanks, Daniil

**Comment by luckyQing** [comment]
I have implemented the functionality I need based on your suggestions and can support multiple levels of nested generics. E.g:`Req<BasePageReq<App<List<String>>>>`.Thank you.

**Comment by daivanov** [comment]
Ok, not sure what was the problem, but it is great that you have fixed it.

Thanks, Daniil
