### ISSUE TITLE
Javadoc inconsistencies with some type manufacturer classes

### ISSUE THREAD

**Issue by mjustin** [mtedone/podam#285]
A number of the type manufacturer classes have class-level Javadoc descriptions that don't match their types.  These appear to be copy/paste errors.

For example, [`ArrayTypeManufacturerImpl`](https://javadoc.io/doc/uk.co.jemos.podam/podam/latest/uk/co/jemos/podam/typeManufacturers/ArrayTypeManufacturerImpl.html) says that it's the "Default collection type manufacturer", rather than the "Default array type manufacturer".

Inconsistent classes:

| Type | Javadoc |
| --- | --- |
| `ArrayTypeManufacturerImpl` | Default collection type manufacturer. |
| `LongTypeManufacturerImpl` | Default int type manufacturer. |
| `MapTypeManufacturerImpl` | Default collection type manufacturer. |
| `TypeTypeManufacturerImpl` | Default byte type manufacturer. |

**Comment by daivanov** [comment]
Fixed in podam 7.2.5.
