### ISSUE TITLE
hints on how to migrate from v6.0.1.RELEASE to v.7.2.4.RELEASE with customized AbstractRandomDataProviderStrategy

### ISSUE THREAD

**Issue by bseiller** [mtedone/podam#286]
We're currently using Podam 6.0.1.RELEASE and plan to migrate to a current version.
As we have **some** members in **some** classes that only allow specific values (think frontend-facing POJO as representation of an enum) we created customized extensions of AbstractRandomDataProviderStrategy in our tests as seen below.
First tests with 7.2.4.RELEASE have shown that AbstractRandomDataProviderStrategy changed considerably (~~getStringValue~~ => getTypeValue) in the new version.
Is there a way to migrate our existing strategy classes and if so how would it be done?
Just overriding getTypeValue instead of getStringValue forces us to use (T) casts, which feels rather hacky.
If there is no way to keep the existing code, what would be the correct way of producing specific values for certain members?

I've seen that annotations are a possibility but I must admit I don't like the idea of adding `@Podam...` annotations to our DTOs as this introduces a general dependency to those classes/modules that only is needed in the test context.
Also I'd prefer to keep the knowledge of which member values are valid outside of the POJOs.

Any help is very appreciated - maybe there are some examples or some documentation I haven't spoted yet.

Finally: I really like using Podam, creating tests objects completely by hand is just such a chore!

```
final class RoleNameStrategy extends AbstractRandomDataProviderStrategy {
    @Override
    public String getStringValue(final AttributeMetadata attributeMetadata) {
        if (attributeMetadata.getPojoClass().equals(Role.class)
                && attributeMetadata.getAttributeName().equals("roleName")) {
            return Role.GUEST.toString();
        } else if ("userGenerated".equals(attributeMetadata.getAttributeName())
                    || "available".equals(attributeMetadata.getAttributeName())) {
            return random.nextBoolean() ? "Y" : "N";
        }
        return super.getStringValue(attributeMetadata);
    }
}
...
// usage
PodamFactory factory = new PodamFactoryImpl(new MPTRoleNameStrategy());
```

**Comment by daivanov** [comment]
Hi,

  In versions 7.x.x you would need to extend StringTypeManufacturerImpl with your implementation and replace default string type manufacturer of the factory with it by doing something like this

    TypeManufacturer<?> customStringManufacturer = new CustomStringTypeManufacturerImpl();
    factory.addOrReplaceTypeManufacturer(String.class, customStringManufacturer);

Thanks, Daniil

**Comment by bseiller** [comment]
Thank you very much - I looked into StringTypeManufacturerImpl and that will do nicely!
