### ISSUE TITLE
GenericPojo is missing generic type arguments, expected [F, S], provided []

### ISSUE THREAD

**Issue by wubin1989** [mtedone/podam#293]
Thanks for this awesome project!
I got an exception when I ran below code copied from https://mtedone.github.io/podam/index.html

```
ParameterizedType stringLongGenericPojoType =
        new PodamParameterizedType(GenericPojo.class, String.class, Long.class);

PodamParameterizedType listBooleanType = new PodamParameterizedType(List.class, Boolean.class);

ParameterizedType IntegerBooleanListMapType =
    new PodamParameterizedType(Map.class, Integer.class, listBooleanType);

PodamFactory factory = new PodamFactoryImpl();
GenericPojo<GenericPojo<String, Long>, Map<Integer, List<Boolean>>> pojo =
    factory.manufacturePojo(GenericPojo.class, stringLongGenericPojoType, IntegerBooleanListMapType);
```

Is it a bug? Or Am I missing something? Please kindly have a look.
Thank you!

**Comment by wubin1989** [comment]
Any update?

**Comment by daivanov** [comment]
Hi,

  Sorry for a delay. Yes, this looks like a problem with types resolution.

Thanks, Daniil

**Comment by wubin1989** [comment]
Hi Daniil,
When will this bug be fixed? Do you have any plan in the near future?

Thanks, Will

**Comment by daivanov** [comment]
Hi,

   This is pretty complex issue. I  will try to look at that on weekend.
   But did you try alternative call without PodamParameterizedType and just provide list of generic types?
   
 Thanks, Daniil
