### ISSUE TITLE
Adding Type Manufacturer does not override @Pattern default

### ISSUE THREAD

**Issue by daz96050** [mtedone/podam#295]
When adding a new Type Manufacturer using the podam docs at "Defining an attribute-level strategy with DataProviderStrategy", all fields on classes being manufactured that have a `@Pattern` annotation are ignored by the manufacturer, automatically returning `null`

**Comment by daivanov** [comment]
Hi,

  We do not support filling @Pattern annotated attributes due to missing reverse regular expression string contruction implementation. How do  you exactly define DataProviderStrategy?
  
  Thanks, Daniil

**Comment by daivanov** [comment]
Closing the issue due to lack of the response
