### ISSUE TITLE
Optional<List<String>> generated as Optional<List<Object>>

### ISSUE THREAD

**Issue by kortov** [mtedone/podam#303]
Hello, I stumbled upon a bug, where Optional<List<String>> as field is manufactured as Optional<List<Object>>. I expected Optional<List<String>> there. Here's a repro https://github.com/kortov/podam-list-bug-repro/blob/main/bug-repro/src/test/java/org/example/OptionalTest.java#L21

![image](https://user-images.githubusercontent.com/6348215/159719693-0d1c76ed-84a5-4f5a-b19c-0363f855a3c6.png)

I know that Optional as a field is a bad practice but actually, I wrote for my purposes a similar to Optional generic class and found this bug with podam and I changed class to Optional for clarity.

**Comment by daivanov** [comment]
Fixed in podam 7.2.9

**Comment by kortov** [comment]
Thank you!
