### ISSUE TITLE
CharSequence are not instanciated by default PodamFactory

### ISSUE THREAD

**Issue by marcelmaatkamp** [mtedone/podam#310]
Apache Avro uses CharSequence for string-type attributes when (de-)serializing java pojo's. Testing these with Podam requires a 'CharSequenceTypeManufacturer' which is currently missing:

```WARN u.c.jemos.podam.api.PodamFactoryImpl - Cannot instantiate a class interface java.lang.CharSequence. Resorting to uk.co.jemos.podam.api.NullExternalFactory external factory```

**Comment by marcelmaatkamp** [comment]
I have made a pull-request #309 which implements CharSequenceTypeManufacturerImpl and a test-case.

**Comment by daivanov** [comment]
Hi,

  CharSequence is an interface implemented by String and we already have StringTypeManufacturerImpl, which is able to produce objects of desired types.

  In the pull requests you test getClassInfo(), but not actual manufacturing.
  
Thanks, Daniil

**Comment by daivanov** [comment]
Fixed in7.2.11-RELEASE or later
