### ISSUE TITLE
Replace dependencies for javax with jakarta

### ISSUE THREAD

**Issue by Christoph-W** [mtedone/podam#317]
Several compile dependencies and imports use `javax` packages that moved to `jakarta`.
Is it possible to provide a variant with `jakarta` support?

**Comment by daivanov** [comment]
Hi,

  This question essentially boils down to dropping Java 6 and Java 7 support.

Thanks, Daniil

**Comment by Christoph-W** [comment]
Security support for Java 7 ended on July 31, 2022.
Java 8 LTS release is supported until December 31, 2030.

**Comment by daivanov** [comment]
Fixed in Podam 8.0.0 or later
