### ISSUE TITLE
Complete PodamAnnotation Target value to allow lombok full usage

### ISSUE THREAD

**Issue by liam-kincaid** [mtedone/podam#321]
May you change the PodamAnnotation from:
`
        package uk.co.jemos.podam.common;

        import java.lang.annotation.Documented;
        import java.lang.annotation.ElementType;
        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;
        import java.lang.annotation.Target;

        /**
         * Annotation to mark PODAM annotations.
         * 
         * 
         * @author maxdidato
         * 
         */
        @Documented
        @Target({ElementType.ANNOTATION_TYPE})
        @Retention(RetentionPolicy.RUNTIME)
        public @interface PodamAnnotation {
        }
`

to:
`
        package uk.co.jemos.podam.common;

        import java.lang.annotation.Documented;
        import java.lang.annotation.ElementType;
        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;
        import java.lang.annotation.Target;

        /**
         * Annotation to mark PODAM annotations.
         * 
         * 
         * @author maxdidato
         * 
         */
        @Documented
        @Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD})
        @Retention(RetentionPolicy.RUNTIME)
        public @interface PodamAnnotation {
        }
`
to be use with "lombok". 
The addition of ElementType.METHOD allow the use on parameter "onMethod_" in lombok initialisation.

**Comment by daivanov** [comment]
Hi,

  PodamAnnotation is an annotation to annotate other annotations. It is not supposed to be applied to the methods. So @Target is correct.

Thanks, Daniil

**Comment by liam-kincaid** [comment]
In this case, you could change all over annotation, like PodamIntValue, etc
Is-it possible ?

**Comment by daivanov** [comment]
In my understanding you should be doing something like this with lombok

```
import lombok.Getter;
import lombok.Setter;
import uk.co.jemos.podam.common.PodamIntValue;

public class Example {

  @Getter @Setter @PodamIntValue(minValue = 0, maxValue = 10) private int value;
  
}
```

I'm not sure why there is a need for on onMethod_ parameter.

Thanks, Daniil

**Comment by liam-kincaid** [comment]
Ok, I explain, I use a custom build method in a builder with hibernate validation.
As you guest, I use @With. Read a sample
[User.tar.gz](https://github.com/mtedone/podam/files/13801481/User.tar.gz)

This illustrate my demand

**Comment by daivanov** [comment]
You have class User with constructor

`User(final UserBuilder builder)`

And class UserBuilder with a constructor
`public UserBuilder(@NotNull final User user)`

This cannot work. But again I don't see a reason why you try to add podam annotations to a method.

Thanks, Daniil

**Comment by liam-kincaid** [comment]
I use delombok and I saw my bad.
You could close this Issue.
