### ISSUE TITLE
Compilation with bzlmod

### ISSUE THREAD

**Issue by liam-kincaid** [mtedone/podam#322]
Also add Bazel mod compilation. I may help if needed

**Comment by daivanov** [comment]
Hi,

  I'm not sure what is Bzlmod compilation in this context.

Thanks, Daniil

**Comment by liam-kincaid** [comment]
it hope to you. Thanks for reactivity

**Comment by daivanov** [comment]
Podam is not using Bazel and you did not describe what kind of problem you are facing with your Bazel project. I have a feeling this is not really a valid problem for Podam.

Thanks, Daniil

**Comment by liam-kincaid** [comment]
It was a proposition, not a Issue. The idea his to have both maven and bazel ofcourse. Due to two different type of registry.
Close the feature if yo want
