### ISSUE TITLE
Improve AttributeMetaData object

### ISSUE THREAD

**Issue by bibounde** [mtedone/podam#57]
In order to create strategies without annotate our POJOs with Podam annotations, it would be interesting to have access to class type in AttributeMetaData.

Today, AttributeMetaData contains only:

* annotations
* attribute type
* attribute name

**Comment by mtedone** [comment]
Hi, in 5.2.0.RELEASE you can do the following: 

1) Create your own ClassInfoStrategy that extends AbstractClassInfoStrategy
2) Set a collection of either/both annotations or fields you want to exclude (fields will be excluded by name)
3) Assign the strategy to the factory
4) Generate your POJO
