### ISSUE TITLE
Podam Utils: Problem with filing boolean data.

### ISSUE THREAD

**Issue by bkraszewski** [mtedone/podam#68]
Hi, thank you for your library, its so helpful in unit testing.
However, I noticed problem with using boolean fields:
I try to generate class using podamFactory.manufacturePojo(Test.class);

i have class:

public class Test{
private boolean visible;

public boolean setVisible(boolean visible){this.visible = visible;}
public boolean isVisible(){ return visible;}
}

There are also other fields, with other types, but boolean fields causes problem:
java.lang.NoSuchMethodException - no getter for field Visible.
I see framework is trying to use getVisible - but for booleans i use isFieldName

I could not find similar issue, if it is not valid, please let me know

**Comment by daivanov** [comment]
Bartosz, could you please verify the issue against latest PODAM release?

**Comment by daivanov** [comment]
Closing.
