### ISSUE TITLE
In the presence of multiple constructors (default + full), give users the ability to choose which one to use

### ISSUE THREAD

**Issue by mtedone** [mtedone/podam#75]
Podam should be intelligent enough to try the fullest constructor first, then if that doesn’t work, it should try the one with less arguments and so on until, if none of the other constructors work, it will choose the default one. 

Example: 

1: BigInteger(int bitLength, int certainty, Random rnd)

2: BigInteger(int signum, byte[] magnitude)
   BigInteger(int numBits, Random rnd)
   BigInteger(String val, int radix)

3: BigInteger(byte[] val)
   BigInteger(String val)

Podam should start with 1. If it can’t build, the first constructor within 2 that succeeds should be used. If that doesn’t work, the fist constructor within 3 should be used and so on until the last choice should be the default constructor (if it exists). This is a very good test case that we should be writing when implement this strategy. The test cases should demonstrate Podam’s ability to “scale down” to the most useful (fullest) constructor up to the point the default constructor will be chosen (last choice).

Regards,
M.

**Comment by mtedone** [comment]
Added constructors to ClassInfo so that these can be used in PodamFactoryImpl to detect preferred one

**Comment by daivanov** [comment]
Currently constructors are being tried from the sorted list by number of parameters. To achieve what you want it's enough to reverse sorting order. It can be done by library users even now if they replace  `Comparator` in strategy with custom one.

**Comment by mtedone** [comment]
Great, let's reverse the order then :-)

**Comment by daivanov** [comment]
Yes, but it should be driven by some configuration settings. There are two apparent options:
1. Configuration should be in DataProviderStrategy
2. Configuration should come from manufacture() call, for example, we can add manufactureFull() method. Which is probably confusing name.

**Comment by mtedone** [comment]
At the strategy level would be good I think, so we don't change interface
signature

**Comment by mtedone** [comment]
Also, please make the changes on the issue-75 branch and then merge to master from there. 

Regards,

**Comment by daivanov** [comment]
Copied Marco's comment from pull request #76:

1) I’d suggest we put a manufacturePojoWithFullData method in the PodamFactory interface. This would set the heavy comparator in the strategy, delegating then the work to manufacturePojo and will make the use of Podam easier (users will still need to write just one line to get their full object) as opposed to them having to get the strategy, set the comparator and set the strategy in the factory.

2) The test for this scenario (in Immutable Pojo), should ideally demonstrate also the fallback from constructor with two arguments to constructor with one and then on default. The way to do this would be to find (or create) a class with three constructors (2 args, 1 arg and default), where non default arguments could not be created. One way to achieve this could be to throw an exception from the constructor of the “unconstructable” class.

3) We should update the html documentation saying that by default Podam creates lightweight constructors and instructions on how to set full constructor strategy. Then I’m happy for you to merge your changes to master and we should release version 5.0.0.RELEASE as we’re changing the interface.

**Comment by daivanov** [comment]
Marco, what do you think about 5.0.0-SNAPSHOT? Is it ready to be released?

**Comment by mtedone** [comment]
Yes

**Comment by daivanov** [comment]
PODAM 5.0.0 released
