### ISSUE TITLE
Separate Annotations and Implementation into separate jars

### ISSUE THREAD

**Issue by mnd999** [mtedone/podam#79]
It would be nice to be able to have only the annotations on the production classpath, importing the actual implementation logic on the test classpath only.

**Comment by mtedone** [comment]
I'm thinking of removing annotations altogether:-) With custom strategies
there's no need. Besides it was an architectural mistake asking users to
annotate their production code with a testing framework

**Comment by mnd999** [comment]
Yeah, i think that might be a better solution, see #80

**Comment by daivanov** [comment]
If that's about PodamExclude annotation, PODAM allows usage of any custom annotations as exclusion annotations. See this test
https://github.com/mtedone/podam/blob/master/src/test/java/uk/co/jemos/podam/test/unit/BooleanUnitTest.java

**Comment by mtedone** [comment]
Daniil I was suggesting to remove all podam annotations

**Comment by daivanov** [comment]
PODAm has quite a free annotations:

* PodamLongValue, PodamBooleanValue, PodamDoubleValue, PodamShortValue, PodamByteValue, PodamCharValue, PodamFloatValue, PodamStringValue, PodamIntValue - can be done through DataProviderStrategy.
* PodamCollection - can be done with DataProviderStrategy
* PodamConstructor - can be done with DataProviderStrategy by manipulating constructor sorting
* PodamExclude - cannot be done with DataProviderStrategy
* PodamStrategyValue - this is very crucial annotation, which is the only conduit for some POJO production and has no replacement

**Comment by mtedone** [comment]
Thank you Daniil. I’ve always built POJOs through Podam without ever annotating my production code. I must assume that the “cannot be done / crucial” annotations are used within Podam itself?

**Comment by mtedone** [comment]
Fixed in 5.2.0.RELEASE. You can now specify your production annotations and Podam will exclude fields annotated with it while filling the POJO
