### ISSUE TITLE
Ability to exclude classes of methods.

### ISSUE THREAD

**Issue by chakrit** [mtedone/podam#82]
With Jackson, it is possible to configure it to only serialize fields (or only getters/setters), see this SO question for example: http://stackoverflow.com/questions/7105745/how-to-specify-jackson-to-only-use-fields-preferably-globally

This does not seem to be possible with the current version of PODAM. Having the ability to specify exclusions rules would be really nice and would allow PODAM to be used with a much larger classes of objects than just basic DTOs/beans/dumb storage classes.

I think this will also solve https://github.com/mtedone/podam/issues/80.

**Comment by chakrit** [comment]
Using `@PodamExclude` is also not feasible since that'd mean going through what many number of classes and applying the attribute to each one of the setter to ignore (each class could have many). It makes much more sense to implement this as a factory-wide rule.

**Comment by daivanov** [comment]
Hi Chakrit!

Thank you for you feedback. In that SO question should we look to customization of object mapper:

    ObjectMapper mapper  = new ObjectMapper();
    mapper.setVisibilityChecker(mapper.getSerializationConfig().getDefaultVisibilityChecker()
                    .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
                    .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
                    .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
                    .withCreatorVisibility(JsonAutoDetect.Visibility.NONE));

or something else?

**Comment by chakrit** [comment]
@daivanov yes, that's what i mean. sorry for not being clear.

**Comment by chakrit** [comment]
For PODAM this could be something like:

```
PodamFactory factory = new PodamFactoryImpl();
factory.excludeSetters(Visibility.Public); // don't touch any setter
```

For #80 it might be done w/ something like this:

```
PodamFactory factory = new PodamFactoryImpl();
factory.exclude(new NameFilter() {
    @Override public boolean include(String name) {
        return name.equals("excludedAttribute");
    }
});
```

**Comment by daivanov** [comment]
But this is only guidance to find fields directly, by setter, getter or by constructor. You won't be able to exclude specific field, which I believe is topic of issue #80, using such approach.

Currently PODAM fills fields, which have setter with name exactly matching to field name. It never fills fields directly.

**Comment by chakrit** [comment]
From #80 

> excluded attributes could be provided by the strategy without having to annotate them

I think this is basically the same. What I want differently is to do it factory-wide instead of at each individual attribute level by way. I guess in other words, there should be a way to configure how PODAM goes out and choose which attribute to fill with random data (or not).

**Comment by daivanov** [comment]
Issue #80 is about excluding attributes by name. You seem to propose to exclude attributes by access modifier of field/setter. Did I get you right?

**Comment by chakrit** [comment]
@daivanov yes. i'm just saying that if you implement it the same way you do datastrategy, you'd also solve #80 as well.

**Comment by daivanov** [comment]
Consider the following POJO

    class Pojo {
        public field1;
        public field2;
        public field3;
        protected field4;
        protected field5;
        protected field6;
        private field7;
        private field8;
        private field9;
    }

How do I exclude, for example, `field8` from this pojo by access modifier?

**Comment by chakrit** [comment]
Lol, sorry if that confuses you. What I mean is that **for me** I want all private fields ignored. So the API could look something like this:

```java
PodamFactory factory = new PodamFactoryImpl();
factory.exclude(new PrivateFieldsFilter());
```

Where `PrivateFieldsFilter` would be something like this:

```java
class PrivateFieldsFilter implements Filter {
    @Override public boolean include(Field field) {
        return Modifier.isPrivate(field.getModifiers());
    }
}
```

This way all private fields `field7`, `field8`, `field9` would be ignored. But since if you implement that, a generic `Filter` interface would provide a solution for #80 as well like this:

```java
PodamFactory factory = new PodamFactoryImpl();
factory.exclude(new Filter() {
    @Override public boolean include(Field field) { // Field is reflection Field object.
        return !field.getName().equals("field8");
    }
});
```

Which would result in _only_ `field8` being ingnored. So you see it's way more flexible to allow some form of filter in there.

**Comment by daivanov** [comment]
Ok, thank you. Now I see it was about generalization of the way how PODAM does object introspection. I believe `Field` is not general enough and it's better to stick to approach similar to Jackson's one.

I have one more question, what is the use cause for exclusion of fields in your case?

**Comment by chakrit** [comment]
@daivanov Sorry for late reply. I have some logic in my setter that breaks if the object is not setup properly, which is the case if I build objects with PODAM.

**Comment by daivanov** [comment]
Typically this is result of bad design. Impossible to say what is the case, but consider the following example.

    class Pojo {
        String field1;
        String field2;
        String field3;
        void setField1(String field1);
        void setField2(String field2);
        void setField3(String field3);
    }

assume only field1 or field2 and field3 together make sense. Otherwise setters will throw IllegalStateException. PODAM will fail since there is hidden logic in calling setters.

But this can be fixed by replacing setters with constructors:

    class Pojo {
        String field1;
        String field2;
        String field3;
        Pojo(field1);
        Pojo(String field2, String field3);
    }

now hidden logic became explicit and PODAM will produce POJO without any problems.

**Comment by daivanov** [comment]
Fixed in PODAM 5.2.0.

**Comment by chakrit** [comment]
@daivanov thank you !

Yeah I realize this is not the best design. But well, I have to live with it so a little configuration support from all the libs here and there really helps : )

**Comment by onacit** [comment]
@daivanov So, How can I do? Examples please?
