### ISSUE TITLE
depth is always reset, which leads to a infinity loop

### ISSUE THREAD

**Issue by bakomchik** [mtedone/podam#93]
podam-5.3.1.RELEASE
/uk/co/jemos/podam/api/PodamFactoryImpl.java:1839
```
	Integer depth = pojos.get(realAttributeType);
			if (depth == null) {
				depth = -1;
			}
			if (depth <= strategy.getMaxDepth(pojo.getClass())) {

				pojos.put(realAttributeType, depth + 1);, //<-- increment depth

				attributeValue = this.manufacturePojoInternal(
						realAttributeType, attributeMetadata, pojos, genericTypeArgsAll);
				pojos.put(realAttributeType, depth);//<-- put -1 again

			} 
```
For example
```
public class A {
    private List<C> listOfC;

    public List<C> getListOfC() {
        return listOfC;
    }

    public void setListOfC(List<C> listOfC) {
        this.listOfC = listOfC;
    }
}

public class B {
    List<A> listOfC;

    public List<A> getListOfC() {
        return listOfC;
    }

    public void setListOfC(List<A> listOfC) {
        this.listOfC = listOfC;
    }
}

public class C {
    List<B> listOfB;


    public List<B> getListOfB() {
        return listOfB;
    }

    public void setListOfB(List<B> listOfB) {
        this.listOfB = listOfB;
    }
}



```
next snippet will cause infinity loop(!= StackOverflowError)

```
    @Test
    public void testLoop()  {
        A a =new  PodamFactoryImpl().manufacturePojo(A.class);
    }
```

**Comment by bakomchik** [comment]
I'm sorry that did not respond in time.

**Comment by daivanov** [comment]
So Travis can execute infinite loop (and all other 159 tests) in 53 seconds.
https://travis-ci.org/daivanov/podam/builds/61324192
I wonder what kind of hardware do they use ;)

**Comment by mtedone** [comment]
The example below results in an infinite loop on my machine as well.

**Comment by mtedone** [comment]
Hi, 

As Daniil was rightly making me notice, this case doesn’t result in an infinite loop, rather in a very long execution. This test asks Podam to create 5 + 5^2 + 5^3 + 5^4 + 5^5 + 5^6 = 19530 elements. I’ve created a new unit test under the issue93 package with the use of PodamCollection(nbrElements = 2) annotation, and the test passes in a couple of seconds. 

This issue can be closed.

Regards,

**Comment by daivanov** [comment]
Changing log message in NullExternalFactory from warn to debug level gives 10% performance increase.

**Comment by daivanov** [comment]
So in other words this POJO requires too much work to be done and this works takes time.
In 5.4.0 it will be ~20% faster, but still not immediate. To deal with that one can do the following:
1. Fix the architecture being testing.
2. Tell Podam to fill less than 5 elements per list. It cab be done with @PodamCollection or @Size annotations. Or alternatively RandomDataProviderStrategy has setNumberOfCollectionElements(int) method.
3. Change depth of filling. By default it's 1, so you can change it to 0 with RandomDataProviderStrategy.setMaxDepth(int) method.

As a side note, according to profiling report it seems approximately 75% or test run time is taken by Maven Surefire Plugin doing some test report formatting. So if you say it takes 12 minutes on your machine, without surefire it will be only 3 minutes.

**Comment by daivanov** [comment]
I did some performance improvements. On April 30th the loop was taking 42 seconds on my PC (with logs disabled). In the latest commit it's 12 seconds on my PC (with logs disabled).
